#!/bin/bash
osadm router --create --credentials=$OPENSHIFTCONFIG -n default
osadm registry --create --credentials=$OPENSHIFTCONFIG -n default
osc create -f /sspeiche/image-streams-centos7.json -n openshift
yum -y install httpd-tools
useradd sspeiche
touch /etc/openshift-passwd
htpasswd -b /etc/openshift-passwd sspeiche redhat
