#!/bin/bash
# Create the router and registry, add a new user and htpasswd 'redhat'
NEWUSER=sspeiche
osadm router --create --credentials=$KUBECONFIG -n default
osadm registry --create --credentials=$KUBECONFIG -n default
osc create -f /$NEWUSER/code/src/github.com/openshift/origin/examples/image-streams/image-streams-centos7.json -n openshift
yum -y install httpd-tools
useradd $NEWUSER
touch /etc/openshift-passwd
htpasswd -b /etc/openshift-passwd $NEWUSER redhat
